cluster:
  name: "main"
  consul:
    address: '${env.CONSUL_HTTP_ADDR}'
  nodeId: "${env.NODE_NAME}"
  advertiseIp: '${env.CSB_IP}'
  http:
    listen: '${env.CSB_IP}:18080'
    authToken: "change-me"
  logRoot: '${env.LOG_DIR}/${env.CONSOLE_ID}'

timing:
  leaderLockTtl: "10s"
  candidateTtl: "15s"
  healthTtl: "15s"
  reconcileEvery: "3s"

node:
  tags:
    site: "ankara"
    rack: "r1"
    disk.ssd: "true"
    allow.kafka: "true"
    allow.mongo: "true"

maintenance:
  localEnabled: false
  localReason: ""

constraints:
  kafka:
    - { key: "allow.kafka", op: "equals", value: "true" }
  mongo:
    - { key: "allow.mongo", op: "equals", value: "true" }

kafka:
  enabled: false
  slotServicePrefix: "kafka"   # kafka-1, kafka-2, kafka-3
  binary: "H:/cots/kafka/bin/windows/kafka-server-start.bat"
  storageFormatBinary: "H:/cots/kafka/bin/windows/kafka-storage.bat"
  logDir: "H:/pak/infra/data/kafka/%NODE%/logs"
  metaLogDir: "D:/works/mongoctl/data/kafka/1/meta"
  configPath: "H:/pak/infra/data/kafka/%NODE%/server.properties"
  inspectTimeout: "2s"
  startArgs: []
  stopMode: "terminate"  # terminate|interrupt (interrupt is best-effort)

mongo:
  enabled: true
  slotServicePrefix: "mongo"   # mongo-1, mongo-2, mongo-3
  binary: '${env.MONGO_TOOLS}/mongod.exe'
  dbPath: '${env.MONGO_DB_PATH}'
  port: ${env.MONGO_PORT}
  bind: '${env.MONGO_ADDR}'
  inspectTimeout: "2s"
  startArgs: []
  stopMode: "terminate"
