// Code generated by xstate2stateless; DO NOT EDIT.
// Source: state.json

package repl

import (
	"context"
	"fmt"

	"github.com/qmuntal/stateless"
)

type State string
type Trigger string

const (
	StateFailed     State = "failed"
	StateInit       State = "init"
	StateRunning    State = "running"
	StateSpawnLocal State = "spawnLocal"
)

const (
	TriggerPingOK     Trigger = "pingOK"
	TriggerSpawnError Trigger = "spawnError"
	TriggerStart      Trigger = "start"
)

// ReplControlService is the clean action surface for this generated machine.
// Each XState action becomes one method here.
type ReplControlService interface {
	CollectStatus(ctx context.Context, args ...any) error
	SpawnMongo(ctx context.Context, args ...any) error
}

type ReplControl struct {
	sm  *stateless.StateMachine
	svc ReplControlService
}

// NewReplControl creates an in-memory state machine (state kept inside the machine).
func NewReplControl(svc ReplControlService) *ReplControl {
	m := &ReplControl{
		sm:  stateless.NewStateMachine(StateInit),
		svc: svc,
	}
	m.configure()
	return m
}

// NewReplControlWithExternalStorageAndArgs creates a machine whose state is stored externally.
// "AndArgs" means FireWithArguments forwards args into service action calls and OnEntry/OnExit.
//
// NOTE: Concurrency/locking is up to the caller (e.g. Consul session lock + CAS).
func NewReplControlWithExternalStorageAndArgs(
	getState func(ctx context.Context) (State, error),
	setState func(ctx context.Context, st State) error,
	svc ReplControlService,
) *ReplControl {
	getAny := func(ctx context.Context) (any, error) {
		return getState(ctx)
	}
	setAny := func(ctx context.Context, v any) error {
		st, ok := v.(State)
		if !ok {
			return fmt.Errorf("external storage setState: expected State, got %T", v)
		}
		return setState(ctx, st)
	}

	m := &ReplControl{
		sm:  stateless.NewStateMachineWithExternalStorage(getAny, setAny),
		svc: svc,
	}
	m.configure()
	return m
}

func (m *ReplControl) configure() {
	// State hooks: entry/exit
	{
		cfg := m.sm.Configure(StateFailed)
	}
	{
		cfg := m.sm.Configure(StateInit)
	}
	{
		cfg := m.sm.Configure(StateRunning)
		cfg.OnEntry(func(ctx context.Context, args ...any) error {
			if m.svc == nil {
				return nil
			}
			if err := m.svc.CollectStatus(ctx, args...); err != nil {
				return err
			}
			return nil
		})
	}
	{
		cfg := m.sm.Configure(StateSpawnLocal)
		cfg.OnEntry(func(ctx context.Context, args ...any) error {
			if m.svc == nil {
				return nil
			}
			if err := m.svc.SpawnMongo(ctx, args...); err != nil {
				return err
			}
			return nil
		})
	}

	// Transitions
	m.sm.Configure(StateInit).
		Permit(TriggerStart, StateSpawnLocal)
	m.sm.Configure(StateSpawnLocal).
		Permit(TriggerPingOK, StateRunning)
	m.sm.Configure(StateSpawnLocal).
		Permit(TriggerSpawnError, StateFailed)
}

func (m *ReplControl) State() State {
	s, _ := m.sm.State().(State)
	return s
}

// Fire fires a trigger without arguments.
func (m *ReplControl) Fire(ctx context.Context, t Trigger) error {
	return m.FireWithArguments(ctx, t)
}

// FireWithArguments fires a trigger and forwards args into service calls.
func (m *ReplControl) FireWithArguments(ctx context.Context, t Trigger, args ...any) error {
	from := m.State()

	if err := m.sm.FireCtx(ctx, t, args...); err != nil {
		return fmt.Errorf("fire %s from %s: %w", t, from, err)
	}

	to := m.State()

	// Transition actions (direct service calls)
	if m.svc != nil {
		switch {
		}
	}

	return nil
}
